name: update-pr-comment

on:
  pull_request:

jobs:
  update-pr-comment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update PR commit message
        uses: shiron-dev/actions/update-pr-comment@v1.1.0
